title: "라떼하우스"
description: "AI 자동매매, 감성분석, 클라우드 프로젝트 정리"
theme: null
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

locale: "ko"
markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "mint"

# 사용자 루트 URL이니까 baseurl은 공백
baseurl: ""

# 상단 메뉴
header_pages:
  - index.md
  - projects.md
  - about.md

# 기본 레이아웃
defaults:
  - scope:
      path: ""
    values:
      layout: single
